### ISSUE TITLE
[SPEC] Formato de inputs

### ISSUE THREAD

**Issue by WashingtonARamos** [RafaelEstevamReis/Simple.Brazilian#3]
Atualmente há uma discrepância entre o formato de input nas classes `CPF` e `CNPJ` - uma aceita apenas dígitos e a outra aceita dígitos com máscara. É importante discutir o formato dos inputs neste momento para que não haja mudanças futuras quando a lib puder ser usada em produção e para não haver inconsistências entre uma API e outra. Os meus pontos pelos quais deveríamos aceitar apenas dígitos:

### Simplicidade
O método assumir que irá receber somente os dígitos permite uma implementação mais simples e direta, sem ter que se preocupar com a sanitização do input no caso de haver ou não uma máscara aplicada.

### Um método, uma função
O método que verifica se o documento é válido deveria verificar se o documento é válido, não se ele está no formato correto **e** é válido. Para isto um método que verificasse se o documento está no formato correto poderia ser introduzido. Não só isso, a biblioteca já possui métodos para remoção das máscaras, caso o consumidor da biblioteca julgue necessário.

Qualquer decisão que seja tomada é importante para a adequação da biblioteca como um todo.

**Comment by RafaelEstevamReis** [comment]
Enquanto estiver em alfa, nada está definido (ainda)
Porém quanto antes forem definidas as regras, melhor

Vejo a validação de um documento um caso especial de sanitização
Um documento com máscara é tão válido quanto um sem

Com o custo baixo (desempenho) em verificar se é necessário remover a máscara (verificar o comprimento) vejo como uma oferta de praticidade pra quem está chamando a função.
Exemplo de CEP, se o texto de entrada tem mais de 8 caracteres, chama-se a função de remoção

**Comment by RafaelEstevamReis** [comment]
Essas [SPEC] vão ter que virar um "md", se quiser fazer um rascunho
Vou refazer o readme hoje, sugeriram um formato interessante mas a pessoa não quis fazer PR, então vou refazer
Refazendo, já podemos linkar os mds de SPEC

Também não fiz ainda os de estilos de codificação (quais cases usar quando, "limite" de indentação, nomenclaturas, essas coisas
